name: build and upload

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12']
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4


    - name: build GSL
      run: |
        wget https://mirror.ibcp.fr/pub/gnu/gsl/gsl-latest.tar.gz
        tar -xvzf gsl-latest.tar.gz
        cd gsl-2.8
        ./configure
        make
        sudo make install
        cd ..

    - name: Install dependencies
      run: |
        pip install twine
        pip install pycifrw
        pip install six
        pip install diffpy.structure

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      if: runner.os == 'Linux'
      run: |
        pip install numpy
        python setup.py install
        python conda-recipe/run_test.py


